### ISSUE TITLE
Error while generating build using 'ng build --prod'

### ISSUE THREAD

**Issue by rishikeshjadhav** [swimlane/ngx-charts#1365]
**Describe the bug**
Unable to generate builds in production mode using 'ng build --prod' command using Angular 8 and swimlane/ngx-charts version 13.0.2

**To Reproduce**
1. Create empty project using Angular CLI
2. Install swimlane/ngx-charts version 13.0.2
3. Run command 'ng build --prod'

**Expected behavior**
Successfully build should be generated

**Screenshots**
NA

**Demo**
NA

**ngx-charts version**
13.0.2

**Additional context**
Below is the error details:

ERROR in ./node_modules/@swimlane/ngx-charts/fesm2015/swimlane-ngx-charts.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:16631:30)    
    at Object.forEachChild (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:63:16)
    at transformSourceFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83586:24)    at transformRoot (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83606:82) 
    at Object.map (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:499:29)      
    at Object.transformNodes (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89951:33)    
    at D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89912:66
    at runWithCancellationToken (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:90002:24)
    at Object.emit (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89912:20)   
    at Object.transformJavascript (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\helpers\transform-javascript.js:111:13)
    at Object.buildOptimizer (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\build-optimizer.js:119:35)
    at Object.buildOptimizerLoader (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js:36:40)

Any idea around this?

**Comment by rishikeshjadhav** [comment]
@marjan-georgiev  any idea around this?

**Comment by vardhmanonline** [comment]
i am also facing same issue just before the release in production.Anyone please help!!

**Comment by rishikeshjadhav** [comment]
@vardhmanonline i got it working by updating the version in package.json file to 12.0.1

Waiting for fix on latest version.

**Comment by kahanu** [comment]
I  am also having the same issue.  Hoping for a fix soon.

**Comment by MohamedFarid648** [comment]
I downgrade it to 12.0.1
"@swimlane/ngx-charts": "^12.0.1",

then clear cache : 
npm cache clean --force

then install it again :
npm install --save 
 or npm install swimlane/ngx-charts@12.0.1

**Comment by ivanov-v** [comment]
Same bug.
Angular 7
"@swimlane/ngx-charts": "^13.0.4",

**Comment by rdandnayak** [comment]
facing the same issue? any solution?

**Comment by jziggas** [comment]
I am having this issue with version 16.0.0
