### ISSUE TITLE
Angular's i18n tool (ng-xi18n) fails because of an unnecessary file reference

### ISSUE THREAD

**Issue by stephanrauh** [swimlane/ngx-charts#154]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Trying to run ng-xi18n on a small project using ngx-charts fails because d3.d.ts contains a reference path that doesn't exist after publishing the library to npm:
![image](https://cloud.githubusercontent.com/assets/3045767/21719913/7c8cfdbc-d420-11e6-8900-5da1ce579a3b.png)

Stephans-MBP:complexCharts stephan$  ./node_modules/.bin/ng-xi18n -p src
Error: Error at /Users/stephan/git/ExploringAngular/charts/complexCharts/node_modules/@swimlane/ngx-charts/release/d3.d.ts:1:1: File '/Users/stephan/git/ExploringAngular/charts/complexCharts/node_modules/@swimlane/node_modules/awesome-typescript-loader/lib/runtime.d.ts' not found.
    at UserError.Error (native)
    at new UserError (/Users/stephan/git/ExploringAngular/charts/complexCharts/node_modules/@angular/tsc-wrapped/src/tsc.js:22:34)
 

**Expected behavior**
ng-xi18n doesn't finish with an error message.

**Reproduction of the problem**
git clone https://github.com/stephanrauh/ExploringAngular.git
cd ExploringAngular
cd charts
cd complexCharts
 ./node_modules/.bin/ng-xi18n -p src

**What is the motivation / use case for changing the behavior?**
Publishing ngx-charts in applications targeting an international audience.

**Please tell us about your environment:**
OSX, node v.6.7.0, npm 3.10.3, Angular CLI 1.0.0-beta.24

* **ngx-charts version:** x.x.x
3.0.3

* **Angular version:** 2.x.x
2.4.0

* **Browser:** [all]
(not a browser problem)

* **Language:** [TypeScript 2.0.3]

**Comment by stephanrauh** [comment]
Simply deleting the first line of d3.d.ts solves the problem. It's not really needed. Maybe this line has been introduced by someone using Visual Studio Code, possibly in another project.

**Comment by amcdnl** [comment]
Ya, @ocombe added it. any thoughts on how to remove but get typings still?

**Comment by ocombe** [comment]
it was a loooong time ago, I think it's safe to remove it now with recent versions of typescript

**Comment by marjan-georgiev** [comment]
@stephanrauh I'm getting a different error running `./node_modules/.bin/ng-xi18n -p src`

```
Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in /Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in /Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/platform-browser/testing/browser.d.ts, resolving symbol BrowserTestingModule in /Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/platform-browser/testing/browser.d.ts
    at simplifyInContext (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:25569:27)
    at StaticReflector.simplify (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:25581:17)
    at StaticReflector.annotations (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:25077:64)
    at NgModuleResolver.resolve (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:17557:86)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:18058:64)
    at CompileMetadataResolver.getNgModuleSummary (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:18014:56)
    at /Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:18104:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:18099:53)
    at addNgModule (/Users/marjan/Projects/ExploringAngular/charts/complexCharts/node_modules/@angular/compiler/bundles/compiler.umd.js:24839:62)
Extraction failed
```

**Comment by stephanrauh** [comment]
@marjan-georgiev The error message doesn't ring a bell. I'd love to help you to fix this error, but this particular error isn't my primary field of expertise, so don't expect me to be able to do a lot. But still, maybe I'll manage to have a look at it tomorrow. Just tell me if I can help you. If not, I'd like to concentrate on my two outstanding pull-requests (lines for the x- and y-coordinates and more flexible tooltips).

**Comment by ocombe** [comment]
@marjan-georgiev I think it means that you're using an anonymous function inline somewhere (probably in a ngModule definition), when you should use a reference to an exported function instead.
Declaire this function, export it, and use it as a reference

**Comment by the-ult** [comment]
Running `npm run lint` / `ng lint` with angular-cli gives the following error (seems related)
```console
Error: Error at ./node_modules/@swimlane/ngx-charts/release/d3.d.ts:1:1: File './node_modules/@swimlane/ngx-charts/node_modules/awesome-typescript-loader/lib/runtime.d.ts' not found.
    at Runner.run (..\node_modules\tslint\lib\runner.js:91:27)
    at Object.<anonymous> (..\node_modules\tslint\lib\tslint-cli.js:138:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\dev\bereslim\bsm-ui\node_modules\tslint\bin\tslint:3:1)
```

```console
                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.26
node: 6.9.1
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/flex-layout: 2.0.0-beta.4
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

@swimlane/ngx-charts: 4.0.3
```

**Comment by oacevedo** [comment]
you should exclude test.ts in your tsconfig.json file 
`"exclude": [
    "node_modules",
    "src/app/main.prod.ts",
    "test.ts"
  ]`

**Comment by marjan-georgiev** [comment]
This should be resolved now. If anyone is still seeing it please let me know.

**Comment by sankumar** [comment]
Hi Team,
I am getting below "trans-unit"  in messages.xlf file. How to exclude node_modules while extract i18n strings using the command "ng xi18n --output-path src/locale". please help me on this issue
 <trans-unit id="ngb.alert.close" datatype="html">
        <source>Close</source>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.d.ts</context>
          <context context-type="linenumber">3</context>
        </context-group>
      </trans-unit>
