### ISSUE TITLE
Lazy loading NgxChartsModules causes NullInjectorError

### ISSUE THREAD

**Issue by yusijs** [swimlane/ngx-charts#1733]
**Describe the bug**
When trying to lazy load a component using NgxChartModule, the below error is thrown and tooltips are not working

> ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionService -> InjectionService -> InjectionService]: 
>   NullInjectorError: No provider for InjectionService!

InjectionService is not exported in the public_api, so not able to provide it manually. Also tried importing the tooltip module etc, but no luck. 

**To Reproduce**
```html
<button (click)="loadComponent()">Load</button>
<ng-template #vcr></ng-template>
```

```ts

constructor(private resolver: ComponentFactoryResolver) {}

public async loadComponent() {
      const { GraphComponent } = await import(`./graph/graph.component`);
      const factory = this.resolver.resolveComponentFactory(GraphComponent);
      this.graph = this.vcr.createComponent(factory);
      this.graph.instance.chartData$ = this.chartData$;
}
```

**Expected behavior**
Graph renders with working tooltips and no stack trace

**Screenshots**
![image](https://user-images.githubusercontent.com/11261560/151632053-22c5a84a-b4ce-40ec-b88f-43d269e33582.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
20.0.1

**Additional context**

**Comment by honibis** [comment]
I solved by editing the source code of ngx-charts library.
Replaced the @Injectable() decorator with:
@Injectable({
  providedIn: 'root'
})
for both TooltipService and InjectionService
also removed the providers from TooltipModule:
providers: [InjectionService, TooltipService]

**Comment by robvaneck** [comment]
I'm using a google material dialog, and having the same issue.
When opening a dialog, with a ngx charts line chart inside the dialog... i get this console error

```
core.mjs:7635 ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionService -> InjectionService -> InjectionService]: 
  NullInjectorError: No provider for InjectionService!
    at NullInjector.get (core.mjs:6359:27)
    at R3Injector.get (core.mjs:6786:33)
    at R3Injector.get (core.mjs:6786:33)
    at R3Injector.get (core.mjs:6786:33)
    at ChainedInjector.get (core.mjs:13769:36)
    at lookupTokenUsingModuleInjector (core.mjs:3293:39)
    at getOrCreateInjectable (core.mjs:3338:12)
    at ɵɵdirectiveInject (core.mjs:10871:12)
    at Module.ɵɵinject (core.mjs:4786:60)
    at NodeInjectorFactory.TooltipService_Factory [as factory] (swimlane-ngx-charts.mjs:352:109)
```

**Comment by Wasenshi123** [comment]
> I solved by editing the source code of ngx-charts library. Replaced the @Injectable() decorator with: @Injectable({ providedIn: 'root' }) for both TooltipService and InjectionService also removed the providers from TooltipModule: providers: [InjectionService, TooltipService]

Based on this reply from @emiliobucha , I have created a pull request for it: https://github.com/swimlane/ngx-charts/pull/1861

**Comment by ChrTall** [comment]
@marjan-georgiev 
Do you have the time to look at the PR #1861 ?

**Comment by Delagen** [comment]
@ChrTall I think it work normally in current version. I use lazy loading with manual create ngModuleRef.

**Comment by PierreLucB** [comment]
The problem is still there today

**Comment by majora2007** [comment]
Also having the same issue with Angular 17.

**Comment by swathichattu** [comment]
I am getting same Issue with Angular 18

**Comment by hanuhimanshu** [comment]
I am on angular 19, the following approach worked for me

```
public async loadComponent() {
      const { GraphComponent } = await import(`./graph/graph.component`);
      this.graph = this.vcr.createComponent(GraphComponent, {
            ngModuleRef: createNgModule(NgxChartsModule, this.viewContainerRef.injector), // here you can also use any other appropiate module also like NgxPieChartModule etc
      });
      this.graph.instance.chartData$ = this.chartData$;
}
```

**Comment by DavideLanzoniSacmi** [comment]
Same problem here. I think this needs to be updated as written by @honibis to be used in the new angular version with standalone components
