### ISSUE TITLE
Error when ng build -prod

### ISSUE THREAD

**Issue by Thieus** [swimlane/ngx-charts#302]
**I'm submitting a error**  (check one with "x")
```
[X] bug report =>
[ ] feature request =>
[ ] support request =>
```

**Current behavior**

When ng build -prod i have errors: 
Angular cli error [#5623](https://github.com/angular/angular-cli/issues/5623)

```
ERROR in .../node_modules/@swimlane/ngx-charts/release/pie-chart/advanced-pie-chart.component.ngfactory.ts
 (342,44): Property 'labels' does not exist on type 'AdvancedPieChartComponent'.

ERROR in .../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-label.component.ngfactory.ts (300,67)
: Supplied parameters do not match any signature of call target.

ERROR in .../node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.ngfactory.ts (131,7): Su
pplied parameters do not match any signature of call target.
.../node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.ngfactory.ts (373,50): Property '
big' does not exist on type 'any[]'.
.../node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.ngfactory.ts (376,50): Property '
big' does not exist on type 'any[]'.
.../node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.ngfactory.ts (379,50): Property '
small' does not exist on type 'any[]'.

ERROR in .../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-normalized.component.ngfacto
ry.ts (746,35): Supplied parameters do not match any signature of call target.
.../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-normalized.component.ngfactory.ts (75
0,35): Supplied parameters do not match any signature of call target.
```

**Expected behavior**
Build -prod ok

* **ngx-charts version:** ^4.1.0
* **Angular version:** ^2.3.1

version package.json:
```
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@covalent/charts": "1.0.0-beta.1-1",
    "@covalent/core": "1.0.0-beta.1-1",
    "@covalent/highlight": "1.0.0-beta.1",
    "@swimlane/ngx-charts": "^4.1.0",
    "class-transformer": "^0.1.6",
    "core-js": "^2.4.1",
    "d3": "^4.5.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "moment": "^2.17.1",
    "ng2-charts": "^1.5.0",
    "ng2-datetime-picker": "^0.14.8",
    "ng2-expansion-panels": "0.0.2",
    "primeng": "^2.0.0-rc.3",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "typescript-map": "0.0.3",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.30",
    "@angular/compiler-cli": "^2.3.1",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by btroncone** [comment]
Looks like this is broken with Angular 4 AoT, as addressed here. https://github.com/swimlane/ngx-charts/issues/299

**Comment by envyN** [comment]
Possible Duplicate to #274 . Should be fixed with #281 once patch is released

**Comment by Shiroh1ge** [comment]
Has anyone tried the 5.0.0 build? I've just started using ngx charts and I can't seem to get it to work. Getting `Cannot read property 'length' of undefined` for any chart I tried to use. I'm on `Angular 4.0.1`

**Comment by sfeilmeier** [comment]
@Shiroh1ge: 5.0.0 is working for me. See my package.json: https://github.com/OpenEMS/openems-gui/blob/master/package.json

**Comment by Shiroh1ge** [comment]
@sfeilmeier thanks for sharing! Unfortunately it did not help. It seems the svg is not being rendered properly or something. I can only see a 'Legend' being shown.
![567hyem](https://cloud.githubusercontent.com/assets/14138908/24547004/7cb019ea-1616-11e7-82a7-19f3c7ba0770.png)

**Comment by sfeilmeier** [comment]
@Shiroh1ge: Ok, hard to say, what's wrong. Do you have the code in a git repository, for me to have a look at it?

**Comment by Shiroh1ge** [comment]
@sfeilmeier unfortunately it's a private repo, I was hoping it's a common problem for other users too. I will try to set up a test project to see if it works. Thanks for the help, though!

**Comment by marjan-georgiev** [comment]
Can anyone confirm if this is still an issue please?

**Comment by envyN** [comment]
Nope. Solved with 5.0.0 and my apps' aot builds are running again.

**Comment by marjan-georgiev** [comment]
Awesome, thanks! Closing this.

**Comment by rishikeshjadhav** [comment]
I am getting similar issue with version 13.0.2

Error details:

ERROR in ./node_modules/@swimlane/ngx-charts/fesm2015/swimlane-ngx-charts.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:16631:30)    
    at Object.forEachChild (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:63:16)
    at transformSourceFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83586:24)    at transformRoot (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83606:82) 
    at Object.map (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:499:29)      
    at Object.transformNodes (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89951:33)    
    at D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89912:66
    at runWithCancellationToken (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:90002:24)
    at Object.emit (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\typescript\lib\typescript.js:89912:20)   
    at Object.transformJavascript (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\helpers\transform-javascript.js:111:13)
    at Object.buildOptimizer (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\build-optimizer.js:119:35)
    at Object.buildOptimizerLoader (D:\Projects\UNIDO\code\branches\app\common\ProMIS\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js:36:40)

**Comment by Guling85** [comment]
Hi,
Im also getting the same error as @rishikeshjadhav when running ng build --prod
version 13.0.2
