### ISSUE TITLE
Bug(heat map calendar): Error on example page

### ISSUE THREAD

**Issue by jotatoledo** [swimlane/ngx-charts#314]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Selecting the heat map calendar chart crashes the app

**Reproduction of the problem**

Go to https://swimlane.github.io/ngx-charts/ and select heat map calendar

**General info**
 Chrome Version 57.0.2987.98 (64-bit), w8 64-bit

**Comment by marjan-georgiev** [comment]
I am not seeing any errors there, nor is it crashing the browser for me. What is the error you are seeing?

**Comment by jotatoledo** [comment]
@marjan-georgiev the following:
libs.js:286 ERROR RangeError: Provided date is not in valid range.
    at DateTimeFormat.args (native)
    at t.calendarAxisTickFormatting (https://swimlane.github.io/ngx-charts/app.js:2:3552)
    at Object.eval [as updateRenderer] (ng:///t/t.ngfactory.js:66:24)
    at Object.updateRenderer (https://swimlane.github.io/ngx-charts/libs.js:398:7992)
    at In (https://swimlane.github.io/ngx-charts/libs.js:398:4479)
    at Zn (https://swimlane.github.io/ngx-charts/libs.js:398:6796)
    at Wn (https://swimlane.github.io/ngx-charts/libs.js:398:6600)
    at In (https://swimlane.github.io/ngx-charts/libs.js:398:4390)
    at Zn (https://swimlane.github.io/ngx-charts/libs.js:398:6796)
    at qn (https://swimlane.github.io/ngx-charts/libs.js:398:6336)
    at In (https://swimlane.github.io/ngx-charts/libs.js:398:4499)
    at Zn (https://swimlane.github.io/ngx-charts/libs.js:398:6796)
    at qn (https://swimlane.github.io/ngx-charts/libs.js:398:6336)
    at In (https://swimlane.github.io/ngx-charts/libs.js:398:4499)
    at Zn (https://swimlane.github.io/ngx-charts/libs.js:398:6796)

**Comment by marjan-georgiev** [comment]
Interesting, might be a locale issue. What locale are you using?

**Comment by jotatoledo** [comment]
de(german)

**Comment by judequinn** [comment]
same error here with russian date format.

```
ERROR RangeError: Provided date is not in valid range.
    at DateTimeFormat.args (native)
    at XAxisTicksComponent.webpackJsonp../demo/app.component.ts.AppComponent.calendarAxisTickFormatting (http://localhost:9999/app.js:381:78)
    at Object.eval [as updateRenderer] (ng:///AxesModule/XAxisTicksComponent.ngfactory.js:66:24)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:9999/libs.js:43146:21)
    at checkAndUpdateView (http://localhost:9999/libs.js:42525:14)
    at callViewAction (http://localhost:9999/libs.js:42835:17)
    at execEmbeddedViewsAction (http://localhost:9999/libs.js:42807:17)
    at checkAndUpdateView (http://localhost:9999/libs.js:42521:5)
    at callViewAction (http://localhost:9999/libs.js:42835:17)
    at execComponentViewsAction (http://localhost:9999/libs.js:42781:13)
    at checkAndUpdateView (http://localhost:9999/libs.js:42526:5)
    at callViewAction (http://localhost:9999/libs.js:42835:17)
    at execComponentViewsAction (http://localhost:9999/libs.js:42781:13)
    at checkAndUpdateView (http://localhost:9999/libs.js:42526:5)
    at callViewAction (http://localhost:9999/libs.js:42835:17)
```

it seems that dd-mm-yy date format causes this error.

**Comment by Hypercubed** [comment]
I am hopefull #321 fixes this issue.

**Comment by xucito** [comment]
I have found this problem intermittently on a iOS Macbook 2017 (High Sierra 10.13.4) using both Chrome or Safari with locale is set to "Australian". Oddly enough on windows it works as expected even with Australian. To solve the problem when I populate my data I don't pass a date object but the date to local ("en-US"). 
Ie:
``` 
[{
name: dateObject.toLocaleDateString("en-US"),
series: data
}]
```

As  I cannot replicate it on any other device and the computer can load the demo I will not submit a issue but rather leave this here in-case anyone experiences the same thing.

The original error is shown below:
![image](https://user-images.githubusercontent.com/36687889/39992731-cc0f2aca-5784-11e8-8ecb-60d0627d7176.png)
