### ISSUE TITLE
ngx-charts exception when used with yeoman template: ASPNETCORE-SPA

### ISSUE THREAD

**Issue by CameronHynes** [swimlane/ngx-charts#441]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Install Microsoft's Yeoman template: ASPNETCORE-SPA https://github.com/aspnet/JavaScriptServices
Install ngx-charts, adding a bar chart results in an exception when browsing to site on localhost:5000:

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: MouseEvent is not defined
at Object../src/force-directed-graph/force-directed-graph.component.ts (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:102097:38)
at __webpack_require__ (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89077:30)
at Object../src/force-directed-graph/force-directed-graph.module.ts (C:\Development\d\src\d.SPA\ClientApp\dist\vendor.js:102130:90)
at __webpack_require__ (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89077:30)
at Object../src/ngx-charts.module.ts (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:104625:108)
at __webpack_require__ (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89077:30)
at Object../src/index.ts (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:103676:77)
at __webpack_require__ (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89077:30)
at ./node_modules/base64-js/index.js.exports.byteLength (C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89123:18)
at C:\Development\dd\src\dd.SPA\ClientApp\dist\vendor.js:89126:10
Current directory is: C:\Development\dd\src\dd.SPA

**Expected behavior**

Chart should render without an exception.

**Reproduction of the problem**

https://bitbucket.org/CameronHynes/asp.net-with-angular-2-charts/src reproduced here, not sure how to reproduce the yeoman template on plunkr.

**What is the motivation / use case for changing the behavior?**
Would support Microsoft's Yeoman "ASP.Net Core + Angular 2" template: https://github.com/aspnet/JavaScriptServices
Note that I'm not sure if ngx-charts is responsible for the exception, maybe it's a problem with the config in the Yeoman template? Sorry if it's not an ngx-charts issue, any advice you have would be helpful. I've got no experience in configuring angular / asp.net / webpack and don't know how to dig any deeper and track down the cause.

**Please tell us about your environment:**

Windows 10 64
VS Code
Webpack

* **ngx-charts version:** 5.3.1

* **Angular version:** 4.1.2

* **Browser:** [ Chrome 58 | Firefox 54 ]

* **Language:** [ TypeScript 2.2 | ES5]

**Comment by CameronHynes** [comment]
My mistake, this exception appeared because I wrongly imported NgxChartsModule into app.module.server which won't work since there's no browser on the server to have any 'MouseEvents'. Hence why the MouseEvent was undefined and the exception thrown.

I solved the error by moving NgxChartsImport statements:
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgxChartsModule } from '@swimlane/ngx-charts';

into app.module.client

Feel free to delete this bug request since it was filed in error.

**Comment by sebichondo** [comment]
Thanks @CameronHynes saved me lots of debugging time
