### ISSUE TITLE
Visual Studio 2017 Angular template - MouseEvent is not defined on second run

### ISSUE THREAD

**Issue by nukec** [swimlane/ngx-charts#572]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I run net core app first time it shows chart. I stop app then I re run again, it throws:
**NodeInvocationException: Prerendering failed because of error: ReferenceError: MouseEvent is not defined
at Object../src/force-directed-graph/force-directed-graph.component.ts (D:\CodePlayground\ClientApp\dist\main-server.js:33746:38)
at __webpack_require__ (D:\CodePlayground\ClientApp\dist\main-server.js:20623:30)
at Object../src/force-directed-graph/force-directed-graph.module.ts (D:\CodePlayground\ClientApp\dist\main-server.js:33779:90)
at __webpack_require__ (D:\CodePlayground\ClientApp\dist\main-server.js:20623:30)
at Object../src/ngx-charts.module.ts (D:\CodePlayground\ClientApp\dist\main-server.js:36294:108)
at __webpack_require__ (D:\CodePlayground\ClientApp\dist\main-server.js:20623:30)
at Object../src/index.ts (D:\CodePlayground\ClientApp\dist\main-server.js:35325:77)
at __webpack_require__ (D:\CodePlayground\ClientApp\dist\main-server.js:20623:30)
at ./node_modules/base64-js/index.js.exports.byteLength (D:\CodePlayground\ClientApp\dist\main-server.js:20669:18)
at D:\CodePlayground\ClientApp\dist\main-server.js:20672:10
Current directory is: D:\CodePlayground**

**Expected behavior**
Chart should always been displayed.

**Reproduction of the problem**

Code:
I imported in module:
```
import {BrowserModule} from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {NgxChartsModule} from '@swimlane/ngx-charts';
```

and same modules in ngModule import.

So point is the chars are working on first run then not.

* **ngx-charts version:*6.0.2* 

* **Angular version:** 4.2.5

**Comment by akaco** [comment]
I getting same error on second run 
An unhandled exception occurred while processing the request.

NodeInvocationException: Prerendering failed because of error: ReferenceError: MouseEvent is not defined
at d:\ODX\ClientApp\dist\main-server.js:36477:42

**ngx-charts version:7.0.1
Angular version: 4.4.6

**Comment by marjan-georgiev** [comment]
This should be fixed in the upcoming release.
