### ISSUE TITLE
Compatibility for Angular 5

### ISSUE THREAD

**Issue by mssravan56** [swimlane/ngx-charts#629]
The latest version of ng-x charts expects angular to be less than 5, now that stable version of 5 is released, we need ng-x to be working with angular 5 as well

**Comment by amcdnl** [comment]
cc @marjan-georgiev

**Comment by nitinht1988** [comment]
@mssravan56  What issue you are facing with Angular 5 ? I am having issue with tooltips on chart hover with Angular 5 and ngx-charts version 6.1.0.

Please help!!!

**Comment by HitomiTenshi** [comment]
@marjan-georgiev I have the same issue as @nitinht1988. Tooltips are misplaced on line-charts and bar-charts, and don't show at all on polar charts.

**Comment by jhilscher** [comment]
I have the issue, that the chart isn't rescaling when the window is resized. (view is undefined)
Works on page reload though.

**Comment by marjan-georgiev** [comment]
Version 7.0.0 with support for angular 5 has been released. Please let me know if you run into any issues.

**Comment by MashB** [comment]
Getting below error 
Failed to read JSON file D:/Repositories/DGCMS/src/Web/Dg.Web.B2BPortal/node_modules/@swimlane/ngx-charts/release/polyfills.metadata.json
Error: TypeError: Cannot read property 'version' of null
    at readMetadataFile (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:66:29)
    at Object.readMetadata (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:35:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:413:34)
    at StaticSymbolResolver.getModuleMetadata (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler\bundles\compiler.umd.js:31789:62)
    at StaticSymbolResolver.hasDecorators (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler\bundles\compiler.umd.js:31516:46)
    at analyzeFile (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler\bundles\compiler.umd.js:30063:63)
    at AotCompiler._analyzeFile (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler\bundles\compiler.umd.js:29291:17)
    at AotCompiler.findGeneratedFileNames (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler\bundles\compiler.umd.js:29307:42)
    at Object.findGeneratedFileNames (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler-cli\src\transformers\program.js:392:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (D:\Repositories\DGCMS\src\Web\Dg.Web.B2BPortal\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:325:55)

**Comment by HitomiTenshi** [comment]
@MashB There's PR #639 that is supposed to fix that.

**Comment by nitinht1988** [comment]
I am getting same error as @MashB . I tried running npm install github:HitomiTenshi/ngx-charts#angular5 but seems not working for me.

**Comment by HitomiTenshi** [comment]
@nitinht1988 Did you try to delete your `node_modules` folder and `package-lock.json` file and then running `npm install`? Assuming that your `ngx-charts` dependency is updated in your `package.json` to this line:

```
"@swimlane/ngx-charts": "github:HitomiTenshi/ngx-charts#angular5",
```

If that doesn't work, what Angular version do you use? My custom build is version `7.0.0` which only supports Angular 5.

**Comment by marjan-georgiev** [comment]
Released 7.0.1 with @HitomiTenshi's fix for this.

**Comment by HitomiTenshi** [comment]
@nitinht1988 Well then forget what I said just now 😆 and just update to the latest release. 😄 
Thanks @marjan-georgiev for merging the fix. 👍

**Comment by nitinht1988** [comment]
Thanks @HitomiTenshi @marjan-georgiev  for the quick fix.

**Comment by levytskyy** [comment]
Angular 5, ngx-charts 7.0.1, the error still remains on server rendering
__metadata("design:paramtypes", [MouseEvent]),
ReferenceError: MouseEvent is not defined

**Comment by svsgdev** [comment]
Angular 5 and ngx-charts 7.0.1 , I still have the issue of misplaced tool tip on combo bar and line chart.
I am using mouse event  polyfill but still have misplaced tooltips. 

Browser-IE11
