### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by VovanVovanich** [swimlane/ngx-charts#788]
Hello.
I have the project. It worked till yesterday. But yesterday i got the error :
 `ERROR in Error: Metadata version mismatch for module C:/Users/Вова/home-money/node_modules/@swimlane/ngx-charts/release/index.d.ts, found version 4, expected 3, resolving symbol Shar
edModule in C:/Users/Вова/home-money/src/app/shared/shared.module.ts, resolving symbol SharedModule in C:/Users/Вова/home-money/src/app/shared/shared.module.ts
[0]     at syntaxError (C:\Users\Вова\home-money\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
[0]     at simplifyInContext (C:\Users\Вова\home-money\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
[0]     at StaticReflector.simplify (C:\Users\Вова\home-money\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
[0]     at StaticReflector.annotations (C:\Users\Вова\home-money\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
[0]     at _getNgModuleMetadata (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
[0]     at _extractLazyRoutesFromStaticModule (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
[0]     at C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
[0]     at Array.reduce (<anonymous>)
[0]     at _extractLazyRoutesFromStaticModule (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
[0]     at C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
[0]     at Array.reduce (<anonymous>)
[0]     at _extractLazyRoutesFromStaticModule (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
[0]     at Object.listLazyRoutesOfModule (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
[0]     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Вова\home-money\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
[0]     at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Вова\home-money\node_modules\@ngtools\webpack\src\plugin.js:240:66)
[0]     at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Вова\home-money\node_modules\@ngtools\webpack\src\plugin.js:493:24)
`
That my 'package.json': 
`{
  "name": "home-money",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "server": "json-server --watch db.json --port 3000",
    "dev": "concurrently --kill-others \"npm run start\" \"npm run server\""
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@swimlane/ngx-charts": "^7.1.1",
    "core-js": "^2.4.1",
    "d3": "^5.0.0",
    "moment": "^2.21.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.3",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "concurrently": "^3.5.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
`
and that 'app.module.ts' 
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent } from './app.component';
import { AuthModule } from './auth/auth.module';
import { AppRoutingModule } from './app-routing.module';
import { UsersService } from './shared/services/users.service';
import { AuthService } from './shared/services/auth.service';
import { SystemModule } from './system/system.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
	HttpModule,
	AuthModule,
	AppRoutingModule,
	SystemModule,
	BrowserAnimationsModule    
  ],
  providers: [UsersService, AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
So the question what to do it to work?

![01 04](https://user-images.githubusercontent.com/38005493/38201418-e767c4ee-36a0-11e8-9f3a-814db7c587aa.png)

**Comment by marjan-georgiev** [comment]
You seem to be using angular 4. The latest version of ngx-charts is compatible with angular 5. You can either upgrade your application to angular 5, or downgrade ngx-charts to a version compatible with angular 4. 

@swimlane/ngx-charts 6.1.0 is compatible to angular 4.
