### ISSUE TITLE
Error: StaticInjectorError(AppServerModule)[TooltipService -> InjectionService]:

### ISSUE THREAD

**Issue by BostjanPisler** [swimlane/ngx-charts#975]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
When running angular 6 app with universal the server side code reports the mentioned injector error. It doesn't break the app tho.

```
ERROR { Error: Uncaught (in promise): Error: StaticInjectorError(AppServerModule)[TooltipService -> InjectionService]:
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]:
    NullInjectorError: No provider for InjectionService!
```

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Using angular universal express setup and ngx-charts-bar-vertical-2d in html template.

* **ngx-charts version:** x.x.x
v9.0.0

* **Angular version:** x.x.x
Angular v6.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by arjun-rao** [comment]
This is happening to me too.

**Comment by BostjanPisler** [comment]
One option would be to now include tooltip if it's disabled but this is probably impossible because the service has to be injected before the property is read.

Maybe there is a way to mock the injection service?

**Comment by msalemSIT** [comment]
Having the same issue here .. anyone found a solutions to this issue so far? It only runs in normal development mode, Dev on AOT, and on production fails.

**Comment by romainpurchla** [comment]
I have same problem. 
My workaround for that is used this `--aot=false --build-optimizer=false` for build in prod.

**Comment by muradm** [comment]
I suppose it is related to #18. As it seems that there is a packaging issue. If you look at exception stack traces below, it runtime is running on `umd`s, however as per #18, there seems to be some problem with packaging, as `@swimlane/ngx-charts/release/index.js` is not used, instead `@swimlane/ngx-charts/release/esm.js` is used, which as workaround requires additional transpilation step.

When not bundled yet:
```
ERROR { Error: StaticInjectorError(AppServerModule)[TooltipService -> InjectionService]: 
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: 
    NullInjectorError: No provider for InjectionService!
    at NullInjector.get (node_modules/@angular/core/bundles/core.umd.js:3288:23)
    at resolveToken (node_modules/@angular/core/bundles/core.umd.js:3533:28)
    at tryResolveToken (node_modules/@angular/core/bundles/core.umd.js:3477:20)
    at StaticInjector.get (node_modules/@angular/core/bundles/core.umd.js:3374:24)
    at resolveToken (node_modules/@angular/core/bundles/core.umd.js:3533:28)
    at tryResolveToken (node_modules/@angular/core/bundles/core.umd.js:3477:20)
```

When bundled all-in-one with webpack:
```
ERROR { Error: StaticInjectorError(AppServerModule)[TooltipService -> InjectionService]: 
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: 
    NullInjectorError: No provider for InjectionService!
    at NullInjector.get (dist/apps/backend/main.js:3662:19)
    at resolveToken (dist/apps/backend/main.js:3907:24)
    at tryResolveToken (dist/apps/backend/main.js:3851:16)
    at StaticInjector.get (dist/apps/backend/main.js:3748:20)
    at resolveToken (dist/apps/backend/main.js:3907:24)
```

**Comment by muradm** [comment]
After hours of battle, it seems to be definitely packaging issue. Porting `@swimlane/ngx-charts` to `ng-packagr` solves this issue, #18 and tons of other (and potential) issues :)

**Comment by priyesh9875** [comment]
@muradm Can you create new/fork repo with your mentioned changes

**Comment by ashishpCACTUS** [comment]
Hi @muradm : I am still facing this issue. You have mentioned steps to move ngx-charts to ng-packagr. But not sure we are following all the steps correctly. Is it possible you can provide your codebase of how you achieved the same ?

**Comment by eplatzek** [comment]
This resolved my issue:
https://github.com/swimlane/ngx-graph/issues/145#issuecomment-461361021

**Comment by mtpultz** [comment]
I'm having this issue in `ngx-charts` v16.0 using Ionic 5 with Angular 10.  Using the solution above doesn't work.
